import 'package:flutter/widgets.dart';

class SahaLocalizations {
  SahaLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('ar'), Locale('en')];

  static const _localizedStrings = <String, Map<String, String>>{
    'ar': {
      'home': 'الرئيسية',
      'saved': 'محفوظ',
      'plan': 'برنامجي',
      'inbox': 'الرسائل',
      'profile': 'حسابي',
      'book_field': 'احجز ملعبًا',
      'join_challenge': 'انضم لتحدٍ',
      'street_workout': 'تمارين شارع',
      'walk_routes': 'مسارات مشي',
      'search_hint': 'ماذا تريد أن تمارس اليوم؟',
      'ai_insight': 'تحليل ذكاء اصطناعي',
      'explore_now': 'استكشف الآن',
      'enroll_now': 'اشترك الآن',
      'get_started': 'ابدأ الآن',
      'continue_guest': 'الدخول كضيف',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'show_password': 'إظهار كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'create_account': 'إنشاء حساب',
      'sign_in': 'تسجيل الدخول',
      'filters': 'فلاتر',
      'level': 'المستوى',
      'price': 'السعر',
      'time': 'الوقت',
      'distance': 'المسافة',
      'apply': 'تطبيق',
      'cancel': 'إلغاء',
      'today': 'اليوم',
      'week': 'الأسبوع',
      'month': 'الشهر',
      'see_all': 'عرض الكل',
      'no_results': 'لا توجد نتائج',
      'retry': 'إعادة المحاولة',
      'coachmarks_title': 'جولة سريعة',
      'coachmarks_next': 'التالي',
      'coachmarks_done': 'تم',
      'coachmarks_skip': 'تخطي',
      'coachmarks_tip_quick_actions': 'اختصار لأهم الأفعال',
      'coachmarks_tip_search': 'ابحث في كل شيء',
      'coachmarks_tip_plan': 'ملخص تقدمك',
      'primary_color': 'اللون الرئيسي',
      'dark_mode': 'الوضع الداكن',
      'language': 'اللغة',
      'ai_stub_msg': 'ميزة قادمة: سنعرض تحليلاً متقدمًا لحالتك الرياضية بناءً على نشاطك وقياساتك.',
      'welcome_title': 'مرحبا بك في ساحة',
      'welcome_desc': 'منصة رياضية واحدة للحجز والتحديات ومسارات المشي.',
      'continue': 'متابعة',
      'guest_mode': 'وضع الضيف',
      'password_hint': 'أدخل كلمة المرور',
      'invalid_email': 'يرجى إدخال بريد إلكتروني صحيح',
      'invalid_password': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل وتحتوي على أحرف كبيرة وصغيرة ورقم.',
      'name': 'الاسم',
      'sign_up': 'تسجيل حساب',
      'or': 'أو',
      'book_now': 'احجز الآن',
      'join_now': 'انضم الآن',
      'start_now': 'ابدأ الآن',
      'ai_center': 'مركز الذكاء الاصطناعي',
      'close': 'إغلاق',
      'settings': 'الإعدادات',
      'theme': 'السمة',
      'coachmarks_replay': 'إعادة الجولة',
      'quick_actions': 'إجراءات سريعة',
      'about': 'عن التطبيق',
      'mock_story': 'قصص محترفين',
      'saved_empty': 'لم تحفظ أي عناصر بعد.',
      'plan_overview': 'نظرة عامة على برنامجي',
      'heatmap': 'خريطة الحرارة',
      'weekly_activity': 'نشاط الأسبوع',
      'completed_challenges': 'تحديات مكتملة',
      'next_bookings': 'الحجوزات القادمة',
      'quick_goals': 'أهداف سريعة',
      'inbox_empty': 'لا رسائل جديدة.',
      'profile_badges': 'أوسمتي',
      'profile_activity': 'سجل النشاط',
      'language_ar': 'العربية',
      'language_en': 'الإنجليزية',
      'primary_color_picker': 'اختر لونًا رئيسيًا',
      'search': 'بحث',
      'search_results': 'نتائج البحث',
      'catalog': 'كتالوج الأنشطة',
      'filters_reset': 'إعادة تعيين',
      'duration': 'المدة',
      'duration_any': 'أي مدة',
      'duration_under_30': 'أقل من 30 دقيقة',
      'duration_30_45': '30-45 دقيقة',
      'duration_45_60': '45-60 دقيقة',
      'duration_over_60': 'أكثر من 60 دقيقة',
      'kcal': 'السعرات الحرارية',
      'kcal_any': 'أي سعرات',
      'kcal_under_200': 'أقل من 200 سعرة',
      'kcal_200_350': '200-350 سعرة',
      'kcal_350_500': '350-500 سعرة',
      'kcal_over_500': 'أكثر من 500 سعرة',
      'price_any': 'أي سعر',
      'price_free': 'مجاني',
      'price_under_20': 'أقل من 20 ₪',
      'price_20_40': '20-40 ₪',
      'price_over_40': 'أكثر من 40 ₪',
      'sport_any': 'كل الرياضات',
      'guest_continue': 'تابع كضيف',
      'signin_success': 'تم تسجيل الدخول بنجاح (محاكاة).',
      'ai_cta': 'اكتشف رؤى الذكاء الاصطناعي',
      'book_field_title': 'احجز ملعبك',
      'venues': 'الملاعب',
      'challenges': 'التحديات',
      'all': 'الكل',
      'beginner': 'مبتدئ',
      'intermediate': 'متوسط',
      'advanced': 'متقدم',
      'all_levels': 'كل المستويات',
      'available_slots': 'الأوقات المتاحة',
      'policies': 'السياسات',
      'comment': 'أرسل تعليقًا',
      'save': 'حفظ',
      'reset_defaults': 'إعادة الضبط الافتراضي',
      'confirm_password': 'تأكيد كلمة المرور',
      'password_strength': 'قوة كلمة المرور',
      'strength_weak': 'ضعيفة',
      'strength_good': 'جيدة',
      'strength_strong': 'قوية',
      'password_strength_weak': 'ضعيفة',
      'password_strength_medium': 'متوسطة',
      'password_strength_strong': 'قوية',
      'passwords_mismatch': 'كلمتا المرور غير متطابقتين',
      'tap_to_flip': 'انقر للقلب واستكشاف المزيد',
      'explore_map': 'استكشاف الخريطة',
      'map_overview': 'خريطة الملاعب والمسارات',
      'sport_type': 'نوع الرياضة',
      'pace': 'السرعة',
      'distance_km': 'المسافة (كم)',
      'time_window_morning': 'صباحي',
      'time_window_evening': 'مسائي',
      'loading_more': 'جاري تحميل المزيد...',
      'filters_time_window': 'الفترة الزمنية',
      'share': 'مشاركة',
      'like': 'إعجاب',
      'unlike': 'إلغاء الإعجاب',
      'copy_link': 'انسخ الرابط',
      'link_copied': 'تم نسخ الرابط',
      'deeplink_label': 'رابط المشاركة',
      'error_generic': 'حدث خطأ غير متوقع',
      'sort_by': 'رتب حسب',
      'sort_popular': 'الأكثر شعبية',
      'sort_price_low_high': 'السعر: من الأقل إلى الأعلى',
      'sort_nearest': 'الأقرب',
      'sort_time_soonest': 'أقرب موعد',
      'hydration': 'الترطيب',
      'steps': 'الخطوات',
    },
    'en': {
      'home': 'Home',
      'saved': 'Saved',
      'plan': 'My Plan',
      'inbox': 'Inbox',
      'profile': 'Profile',
      'book_field': 'Book a Field',
      'join_challenge': 'Join a Challenge',
      'street_workout': 'Street Workout',
      'walk_routes': 'Walk Routes',
      'search_hint': 'What do you want to do today?',
      'ai_insight': 'AI Insight',
      'explore_now': 'Explore Now',
      'enroll_now': 'Enroll Now',
      'get_started': 'Get Started',
      'continue_guest': 'Continue as Guest',
      'email': 'Email',
      'password': 'Password',
      'show_password': 'Show Password',
      'forgot_password': 'Forgot password?',
      'create_account': 'Create Account',
      'sign_in': 'Sign In',
      'filters': 'Filters',
      'level': 'Level',
      'price': 'Price',
      'time': 'Time',
      'distance': 'Distance',
      'apply': 'Apply',
      'cancel': 'Cancel',
      'today': 'Today',
      'week': 'Week',
      'month': 'Month',
      'see_all': 'See all',
      'no_results': 'No results',
      'retry': 'Retry',
      'coachmarks_title': 'Quick Tour',
      'coachmarks_next': 'Next',
      'coachmarks_done': 'Done',
      'coachmarks_skip': 'Skip',
      'coachmarks_tip_quick_actions': 'Quick access to core actions',
      'coachmarks_tip_search': 'Search across everything',
      'coachmarks_tip_plan': 'Your progress at a glance',
      'primary_color': 'Primary Color',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'ai_stub_msg': 'Coming soon: advanced AI analysis of your fitness based on your activity & metrics.',
      'welcome_title': 'Welcome to Saha',
      'welcome_desc': 'One sports hub for booking, challenges, walks & insights.',
      'continue': 'Continue',
      'guest_mode': 'Guest Mode',
      'password_hint': 'Enter password',
      'invalid_email': 'Please enter a valid email address.',
      'invalid_password': 'Password must be at least 8 chars with upper, lower and digit.',
      'name': 'Name',
      'sign_up': 'Sign Up',
      'or': 'or',
      'book_now': 'Book Now',
      'join_now': 'Join Now',
      'start_now': 'Start Now',
      'ai_center': 'AI Insight Center',
      'close': 'Close',
      'settings': 'Settings',
      'theme': 'Theme',
      'coachmarks_replay': 'Replay tour',
      'quick_actions': 'Quick actions',
      'about': 'About',
      'mock_story': 'Pro Stories',
      'saved_empty': 'No items saved yet.',
      'plan_overview': 'My Plan Overview',
      'heatmap': 'Heatmap',
      'weekly_activity': 'Weekly Activity',
      'completed_challenges': 'Completed Challenges',
      'next_bookings': 'Next Bookings',
      'quick_goals': 'Quick Goals',
      'inbox_empty': 'No new messages.',
      'profile_badges': 'Badges',
      'profile_activity': 'Activity History',
      'language_ar': 'Arabic',
      'language_en': 'English',
      'primary_color_picker': 'Pick a primary color',
      'search': 'Search',
      'search_results': 'Search Results',
      'catalog': 'Activities Catalog',
      'filters_reset': 'Reset',
      'duration': 'Duration',
      'duration_any': 'Any duration',
      'duration_under_30': 'Under 30 min',
      'duration_30_45': '30-45 min',
      'duration_45_60': '45-60 min',
      'duration_over_60': 'Over 60 min',
      'kcal': 'Calories',
      'kcal_any': 'Any calories',
      'kcal_under_200': 'Under 200 kcal',
      'kcal_200_350': '200-350 kcal',
      'kcal_350_500': '350-500 kcal',
      'kcal_over_500': 'Over 500 kcal',
      'price_any': 'Any price',
      'price_free': 'Free',
      'price_under_20': 'Under 20 ₪',
      'price_20_40': '20-40 ₪',
      'price_over_40': 'Over 40 ₪',
      'sport_any': 'All sports',
      'guest_continue': 'Continue as guest',
      'signin_success': 'Signed in successfully (mock).',
      'ai_cta': 'Discover AI insights',
      'book_field_title': 'Book your field',
      'venues': 'Venues',
      'challenges': 'Challenges',
      'all': 'All',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'all_levels': 'All levels',
      'available_slots': 'Available slots',
      'policies': 'Policies',
      'comment': 'Send a comment',
      'save': 'Save',
      'reset_defaults': 'Reset defaults',
      'confirm_password': 'Confirm password',
      'password_strength': 'Password strength',
      'strength_weak': 'Weak',
      'strength_good': 'Good',
      'strength_strong': 'Strong',
      'password_strength_weak': 'Weak',
      'password_strength_medium': 'Medium',
      'password_strength_strong': 'Strong',
      'passwords_mismatch': 'Passwords do not match.',
      'tap_to_flip': 'Tap to flip for more details',
      'explore_map': 'Explore Map',
      'map_overview': 'Routes & venues map',
      'sport_type': 'Sport type',
      'pace': 'Pace',
      'distance_km': 'Distance (km)',
      'time_window_morning': 'Morning',
      'time_window_evening': 'Evening',
      'loading_more': 'Loading more...',
      'filters_time_window': 'Time window',
      'share': 'Share',
      'like': 'Like',
      'unlike': 'Unlike',
      'copy_link': 'Copy link',
      'link_copied': 'Link copied to clipboard',
      'deeplink_label': 'Share link',
      'error_generic': 'Something went wrong',
      'sort_by': 'Sort by',
      'sort_popular': 'Most popular',
      'sort_price_low_high': 'Price: low to high',
      'sort_nearest': 'Nearest',
      'sort_time_soonest': 'Soonest time',
      'hydration': 'Hydration',
      'steps': 'Steps',
    }
  };

  String get languageCode => locale.languageCode;

  String t(String key) {
    final languageMap = _localizedStrings[locale.languageCode] ?? _localizedStrings['ar']!;
    return languageMap[key] ?? key;
  }

  static SahaLocalizations of(BuildContext context) {
    return Localizations.of<SahaLocalizations>(context, SahaLocalizations)!;
  }
}

class SahaLocalizationsDelegate extends LocalizationsDelegate<SahaLocalizations> {
  const SahaLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'en'].contains(locale.languageCode);

  @override
  Future<SahaLocalizations> load(Locale locale) async => SahaLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<SahaLocalizations> old) => false;
}
